[package]
name = "yes"
version = "0.0.1"
authors = []
description = "Repeatedly output a line with all specified STRING(s), or 'y'."
build = "../../mkmain.rs"

[lib]
name = "uu_yes"
path = "yes.rs"

[dependencies]
clap = "2.32"
uucore = { path = "../uucore" }

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
nix = "0.13.0"
libc = "0.2"

[features]
latency = []
default = []

[[bin]]
name = "yes"
path = "../../uumain.rs"
