[package]
name = "mv"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_mv"
path = "mv.rs"

[dependencies]
getopts = "0.2.18"
fs_extra = "1.1.0"
uucore = "0.0.1"

[[bin]]
name = "mv"
path = "../../uumain.rs"
